container:
  image: node:latest
install_task:
  node_modules_cache:
    folder: node_modules
    #fingerprint_script: cat yarn.lock
    #populate_script: npm install
  script: npm install
test_task:
  node_modules_cache:
    folder: node_modules
    #fingerprint_script: cat yarn.lock
    #populate_script: npm install
  script: npm test
